### ISSUE TITLE
DepositFiles links are dead 

### ISSUE THREAD

**Issue by cooljeanius** [H2CO3/ios-toolchain#1]
They display this message when clicked on: 

> "This file does not exist, the access to the following file is limited or it has been removed due to infringement of copyright."

**Comment by H2CO3** [comment]
Oh, that sucks. Any idea about a service where I could reupload them without removal?

**Comment by rustymagnet3000** [comment]
I agree with @cooljeanius. Delete from your nice readme as that is not a good site.

**Comment by H2CO3** [comment]
This project has long been obsolete; I'm not updating it anymore.
